fantasy_br:
  target: local
  outputs:
    local:
      type: bigquery
      method: oauth
      project: fantasy-br
      dataset: fdmdev_fantasy_br
      location: US
      threads: 4
    dev:
      type: bigquery
      method: service-account
      project: fantasy-br
      dataset: fdmdev_fantasy_br
      location: US
      threads: 4
      keyfile: "{{ env_var('DBT_BIGQUERY_KEYFILE') }}"
    demo:
      type: bigquery
      method: service-account
      project: fantasy-br
      dataset: fdmdemo_fantasy_br
      location: US
      threads: 4
      keyfile: "{{ env_var('DBT_BIGQUERY_KEYFILE') }}"
    prod:
      type: bigquery
      method: service-account
      project: fantasy-br
      dataset: fdmprod_fantasy_br
      location: US
      threads: 4
      keyfile: "{{ env_var('DBT_BIGQUERY_KEYFILE') }}"
